/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/yDEyuUW6IGG
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { CardContent } from "@/components/ui/card"
import { CarouselItem, CarouselContent, CarouselPrevious, CarouselNext, Carousel } from "@/components/ui/carousel"

export function Homepage() {
  return (
    <div key="1" className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <header className="flex justify-between items-center py-6">
        <h1 className="text-3xl font-bold">HEADOUT</h1>
        <nav className="flex space-x-4">
          <Link className="text-sm" href="#">
            English/Intl
          </Link>
          <Link className="text-sm" href="#">
            Help
          </Link>
          <Button className="bg-[#bd1e59] text-white">Sign In</Button>
        </nav>
      </header>
      <div className="flex justify-between items-center mt-6">
        <Input className="flex-grow mr-4" placeholder="Search for experiences and cities" />
        <Button variant="outline">Search</Button>
      </div>
      <div className="flex justify-between items-center mt-6 space-x-4">
        <Button variant="ghost">All categories</Button>
        <Button variant="ghost">Bestsellers</Button>
        <Button variant="ghost">Burj Khalifa Tickets</Button>
        <Button variant="ghost">Aquaventure Tickets</Button>
      </div>
      <div className="mt-8 relative">
        <img alt="Hero Image" className="w-full h-[400px] object-cover rounded-lg" src="/placeholder.svg" />
        <div className="absolute inset-0 flex flex-col justify-center items-center text-center text-white">
          <h2 className="text-2xl font-semibold">Bespoke luxury dining at your convenience</h2>
          <p className="mt-2 text-lg">
            From themed nights at Mundo to a gastronomic journey at the Atmosphere, Burj Khalifa.
          </p>
          <p className="mt-2 text-lg font-medium">Starting at AED 241</p>
        </div>
      </div>
      <div className="mt-8">
        <h3 className="text-xl font-semibold">Curated List</h3>
        <div className="min-w-full">
          <Carousel className="w-full">
            <CarouselContent>
              <CarouselItem>
                <CardContent className="flex flex-nowrap gap-4">
                  <div className="w-[calc(50%-1rem)]">
                    <img
                      alt="Luxury Dining Experience"
                      height="160"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "260/160",
                        objectFit: "cover",
                      }}
                      width="260"
                    />
                    <p className="mt-2">Exclusive Dinner at Armani Hotel</p>
                    <p className="mt-1 text-sm font-medium">$150</p>
                  </div>
                  <div className="w-[calc(50%-1rem)]">
                    <img
                      alt="Luxury Dining Experience"
                      height="160"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "260/160",
                        objectFit: "cover",
                      }}
                      width="260"
                    />
                    <p className="mt-2">Culinary Delights at Pierchic</p>
                    <p className="mt-1 text-sm font-medium">$120</p>
                  </div>
                  <div className="w-[calc(50%-1rem)]">
                    <img
                      alt="Luxury Dining Experience"
                      height="160"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "260/160",
                        objectFit: "cover",
                      }}
                      width="260"
                    />
                    <p className="mt-2">Gourmet Journey at Atmosphere</p>
                    <p className="mt-1 text-sm font-medium">$180</p>
                  </div>
                </CardContent>
              </CarouselItem>
              <CarouselItem>
                <CardContent>
                  <img
                    alt="Luxury Dining Experience"
                    height="160"
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "260/160",
                      objectFit: "cover",
                    }}
                    width="260"
                  />
                  <p className="mt-2">Culinary Delights at Pierchic</p>
                  <p className="mt-1 text-sm font-medium">$120</p>
                </CardContent>
              </CarouselItem>
              <CarouselItem>
                <CardContent>
                  <img
                    alt="Luxury Dining Experience"
                    height="160"
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "260/160",
                      objectFit: "cover",
                    }}
                    width="260"
                  />
                  <p className="mt-2">Gourmet Journey at Atmosphere</p>
                  <p className="mt-1 text-sm font-medium">$180</p>
                </CardContent>
              </CarouselItem>
            </CarouselContent>
            <CarouselPrevious />
            <CarouselNext />
          </Carousel>
        </div>
      </div>
      <div className="mt-8">
        <h3 className="text-xl font-semibold">Top rated experiences you shouldn't miss out</h3>
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4 mt-4">
          <img
            alt="Experience"
            height="180"
            src="/placeholder.svg"
            style={{
              aspectRatio: "260/180",
              objectFit: "cover",
            }}
            width="260"
          />
          <img
            alt="Experience"
            height="180"
            src="/placeholder.svg"
            style={{
              aspectRatio: "260/180",
              objectFit: "cover",
            }}
            width="260"
          />
          <img
            alt="Experience"
            height="180"
            src="/placeholder.svg"
            style={{
              aspectRatio: "260/180",
              objectFit: "cover",
            }}
            width="260"
          />
          <img
            alt="Experience"
            height="180"
            src="/placeholder.svg"
            style={{
              aspectRatio: "260/180",
              objectFit: "cover",
            }}
            width="260"
          />
          <img
            alt="Experience"
            height="180"
            src="/placeholder.svg"
            style={{
              aspectRatio: "260/180",
              objectFit: "cover",
            }}
            width="260"
          />
          <img
            alt="Experience"
            height="180"
            src="/placeholder.svg"
            style={{
              aspectRatio: "260/180",
              objectFit: "cover",
            }}
            width="260"
          />
          <img
            alt="Experience"
            height="180"
            src="/placeholder.svg"
            style={{
              aspectRatio: "260/180",
              objectFit: "cover",
            }}
            width="260"
          />
          <img
            alt="Experience"
            height="180"
            src="/placeholder.svg"
            style={{
              aspectRatio: "260/180",
              objectFit: "cover",
            }}
            width="260"
          />
        </div>
        <div className="flex justify-center mt-4">
          <Button variant="outline">Show more</Button>
        </div>
      </div>
    </div>
  )
}
